football/urls.py
from django.urls import path, re_path

from . import views

app_name = 'football'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tournaments/', views.TournamentsView.as_view(), name='tournaments'),
    re_path(r'^tournaments/(?P<id>[0-9]{1,3})/', views.tournament_single),
    path('create-tournament/', views.form_view, name='create_tournament'),
]

football/models.py
import simplejson as json
from django.db import models
from django.utils.html import format_html
from django.utils.timezone import now
from django.db.models.signals import post_save


class League(models.Model):
    class Meta:
        verbose_name = 'League'
        verbose_name_plural = 'Leagues'

    title = models.CharField(unique=True, max_length=50)
    image = models.ImageField(upload_to='uploads/leagues/', default='no-image.png')

    # To show the media files in the list display in the admin panel:
    def image_tag(self):
        return format_html('<img src="{0}" width="50" height="50" />'.format(self.image.url))

    image_tag.allow_tags = True

    # image_tag.short_description = 'Image'

    def __str__(self):
        return f'{self.title}'


class Team(models.Model):
    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

    title = models.CharField(unique=True, max_length=50)
    image = models.ImageField(upload_to='uploads/teams/', default='no-image.png')
    information = models.TextField(null=True, max_length=500, blank=True)
    league = models.ForeignKey(
        League,
        related_name='League',
        on_delete=models.SET_NULL,
        null=True,
    )

    # To show the media files in the list display in the admin panel:
    def image_tag(self):
        return format_html('<img src="{0}" title="{1}" width="50" height="50" />'.format(self.image.url, self.title))

    image_tag.allow_tags = True

    def __str__(self):
        return f'{self.title}'


class Tournament(models.Model):
    GRID_8X8 = '8x8'
    GRID_4X4 = '4x4'
    TABLE = 'table'

    TOURNAMENT_TYPES = [
        # (GRID_16X16, '16x16'),
        (TABLE, 'Table'),
        (GRID_4X4, 'GRID 8 Teams'),
        (GRID_8X8, 'GRID 16 Teams'),
    ]

    class Meta:
        verbose_name = 'Tournament'
        verbose_name_plural = 'Tournaments'

    title = models.CharField(max_length=50, unique=True)
    info = models.TextField(null=True)
    teams_in = models.ManyToManyField(Team, )
    date_time = models.DateTimeField(default=now, blank=True)
    type = models.CharField(
        max_length=5,
        choices=TOURNAMENT_TYPES,
        default=TABLE,
    )

    def save(self, *args, **kwargs):
        # TODO make things instead signal create_tournament_matches
        super(Tournament, self).save(*args, *kwargs)

    def __str__(self):
        return f'{self.title} type:{self.type}'


class Match(models.Model):
    MATCH_STATUS = (
        (0, 'Pending'),
        (1, 'Done'),
    )

    class Meta:
        verbose_name = 'Match'
        verbose_name_plural = 'Matches'

    title = models.CharField(max_length=50)
    tournament = models.ForeignKey(
        Tournament,
        on_delete=models.CASCADE,
    )
    team_1 = models.ForeignKey(
        Team,
        related_name='Team_1',
        on_delete=models.CASCADE,
    )
    team_2 = models.ForeignKey(
        Team,
        related_name='Team_2',
        on_delete=models.CASCADE,
    )
    team_1_goals = models.SmallIntegerField(
        default=0,
    )
    team_2_goals = models.SmallIntegerField(
        default=0,
    )
    status = models.SmallIntegerField(choices=MATCH_STATUS, default=0)
    date_time = models.DateTimeField(default=now, blank=True)

    def __str__(self):
        return f'{self.title}'


def update_tournament_team_info(tournament_id):
    TournamentTeamInfo.objects.filter(tournament=tournament_id).update(
        won=0, matches=0, drawn=0, lost=0, goal_scored=0, goal_conceded=0, points=0,
    )
    matches = Match.objects.filter(tournament=tournament_id)
    for match in matches:
        if match.status == 0:
            return
        team_1 = TournamentTeamInfo.objects.get(team=match.team_1, tournament=tournament_id)
        team_2 = TournamentTeamInfo.objects.get(team=match.team_2, tournament=tournament_id)
        team_1.matches += 1
        team_1.goal_scored += match.team_1_goals
        team_1.goal_conceded += match.team_2_goals
        team_2.matches += 1
        team_2.goal_scored += match.team_2_goals
        team_2.goal_conceded += match.team_1_goals
        if match.team_1_goals > match.team_2_goals:
            team_1.won += 1
            team_1.points += 3
            team_2.lost += 1
        elif match.team_1_goals < match.team_2_goals:
            team_1.lost += 1
            team_2.won += 1
            team_2.points += 3
        else:
            team_1.drawn += 1
            team_2.drawn += 1
            team_1.points += 1
            team_2.points += 1
        team_1.save()
        team_2.save()


class TournamentTeamInfo(models.Model):
    class Meta:
        verbose_name = 'Team Info'
        verbose_name_plural = 'Teams Info'

    team = models.ForeignKey(
        Team,
        related_name='Team',
        on_delete=models.CASCADE,
    )
    matches = models.SmallIntegerField(
        default=0
    )
    won = models.SmallIntegerField(
        default=0
    )
    drawn = models.SmallIntegerField(
        default=0
    )
    lost = models.SmallIntegerField(
        default=0
    )
    goal_scored = models.SmallIntegerField(
        default=0
    )
    goal_conceded = models.SmallIntegerField(
        default=0
    )
    points = models.SmallIntegerField(
        default=0
    )
    tournament = models.ForeignKey(
        Tournament,
        on_delete=models.CASCADE,
        default=1,
    )


# TODO: create methods save inside models instead signals
# SIGNALS
# signal create matches
def create_tournament_matches(instance, created, **kwargs):
    # if not created:
    #     return
    teams_in = instance.teams_in.all()

    for team_1 in teams_in:
        for team_2 in teams_in:
            if team_1.id is not team_2.id:
                match_title = '{} vs {}'.format(team_1.title, team_2.title)
                Match.objects.create(title=match_title, tournament=instance, team_1=team_1, team_2=team_2)


post_save.connect(create_tournament_matches, sender=Tournament)


def create_tournament_team_info(instance, created, **kwargs):
    # if not created:
    #     return

    for team in instance.teams_in.all():
        TournamentTeamInfo.objects.create(team=team, tournament=instance)


post_save.connect(create_tournament_team_info, sender=Tournament)

football/forms.py
from django import forms
from django_select2.forms import Select2MultipleWidget

from .models import Team, Tournament


class TournamentForm(forms.Form):

    class Meta:
        model = Tournament
        fields = ['title', 'teams']
    # type = forms.ModelMultipleChoiceField(queryset=Tournament.objects.all())
    title = forms.CharField(max_length=50)
    tournament_type = forms.CharField(
        widget=forms.Select(
            choices=Tournament.TOURNAMENT_TYPES
        )
    )
    teams = forms.ModelMultipleChoiceField(queryset=Team.objects.all(), widget=Select2MultipleWidget)

    def clean_teams(self, *args, **kwargs):
        teams = self.cleaned_data.get('teams')

        tournament_type = self.cleaned_data.get('tournament_type')

        if teams.count() < 3:
            raise forms.ValidationError("3 teams is min amount")
        if tournament_type == Tournament.GRID_4X4 and teams.count() is not 8:
            raise forms.ValidationError("This type of competition must include 8 teams")
        return teams

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if Tournament.objects.filter(title=title).exists():
            raise forms.ValidationError('Current title already exist!')
        return title

football/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from .forms import TournamentForm
from .models import *
import simplejson as json


class IndexView(TemplateView):
    template_name = 'football/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class TournamentsView(TemplateView):
    template_name = 'football/tournaments.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tournaments'] = Tournament.objects.all()
        return context


def tournament_single(request, id):
    if request.POST:
        matches = Match.objects.filter(tournament=id)
        post_data = request.POST
        for match in matches:
            match_list = post_data.getlist('match_' + str(match.id))
            match_status = post_data.get('status_' + str(match.id), 0)
            if len(match_list) == 2:
                team_1_goals = match_list[0]
                team_2_goals = match_list[1]
                # Save match
                current_match = Match.objects.get(pk=match.id)
                current_match.team_1_goals = int(team_1_goals)
                current_match.team_2_goals = int(team_2_goals)
                current_match.status = int(match_status)
                current_match.save()
        update_tournament_team_info(id)

    if Tournament.objects.filter(pk=id).exists() is not True:
        return HttpResponseRedirect(reverse('football:tournaments'))
    else:
        tournament = Tournament.objects.get(pk=id)
        teams_statistics = TournamentTeamInfo.objects.filter(tournament=id).order_by('-points')
        teams_list = tournament.teams_in.all()
        match_list = Match.objects.filter(tournament=id)

        context = {
            'tournament': tournament,
            'teams': teams_list,
            'matches': match_list,
            'statistics': teams_statistics,
        }
        return render(request, 'football/tournament.html', context)


def form_view(request):
    form = TournamentForm(request.POST or None)
    context = {'form': form}
    if request.POST and form.is_valid():
        tournament = Tournament()
        tournament.type = form.cleaned_data.get('tournament_type')
        tournament.title = form.cleaned_data.get('title')
        tournament.save()
        teams_list = []
        teams = form.cleaned_data.get('teams')
        for team in teams:
            if Team.objects.filter(pk=team.id).exists():
                teams_list.append(Team.objects.get(pk=team.id))
        tournament.teams_in.set(teams_list)
        tournament.save()
        return HttpResponseRedirect(reverse('football:tournaments'))
    return render(request, 'football/create_tournament.html', context)

football/templates/football/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>
        {% block title %}
        {% endblock %}
    </title>
    {{ form.media.css }}
</head>
<body>

<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'football:index' %}">
                        Home
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'football:create_tournament' %}">
                        Create new
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'football:tournaments' %}">
                        Tournaments
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block body %}
    {% endblock %}

</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
{{ form.media.js }}
</body>
</html>

football/templates/football/create_tournament.html
{% extends 'football/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Create
{% endblock %}

{% block body %}
    <h1>Page create</h1>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Create" class="btn btn-primary">
</form>
{% endblock %}

football/templates/football/index.html
{% extends 'football/base.html' %}
{% block title %}
Home
{% endblock %}

{% block body %}
    <h1>Hello, index</h1>
{% endblock %}

football/templates/football/tournament.html
{% extends 'football/base.html' %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block title %}
{{ tournament.title }}
{% endblock %}
{% block body %}
<h1>{{ tournament.title }}</h1>
<div class="mb-5">
    <div class="container">
        <div class="row">

            {% for team in teams %}
            <div class="col" align="center">
                {{ team.image_tag }}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% if tournament.type == 'table' %}
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="list-tab" data-toggle="tab" href="#list" role="tab" aria-controls="list"
           aria-selected="true">Match list</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
           aria-selected="false">Grid</a>
    </li>
</ul>
<div class="tab-content mt-5" id="myTabContent">
    <div class="tab-pane fade show mt-5 active" id="list" role="tabpanel" aria-labelledby="list-tab">
        <form method="post">
            {% csrf_token %}
            <table class="table table-sm table-hover table-bordered table-dark">
                <thead align="center">
                <th scope="col">Owner</th>
                <th scope="col">Score</th>
                <th scope="col">Guest</th>
                <th scope="col">Match Status</th>
                </thead>
                <tbody align="center">
                {% for match in matches %}

                <tr data-match="{{ match.id }}">
                    <td>{{ match.team_1.title }}</td>
                    <td>
                        <div class="form-group">
                            <input class="col-sm-2" type="number" value="{{ match.team_1_goals }}" min="0"
                                   name="match_{{ match.id }}">
                            -
                            <input class="col-sm-2" type="number" value="{{ match.team_2_goals }}" min="0"
                                   name="match_{{ match.id }}">
                        </div>
                    </td>
                    <td>{{ match.team_2.title }}</td>
                    <td>
                        {% if match.status is 1 %}
                        <input class="match_status" type="checkbox" name="status_{{ match.id }}" value="1"
                               checked="checked">
                        {% else %}
                        <input class="match_status" type="checkbox" name="status_{{ match.id }}" value="1">
                        {% endif %}
                        <label>Completed</label>
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>
            <div class="mb-5">
                <button class="btn btn-success" id="complete_matches">Complete matches</button>
                <button class="btn btn-primary" id="update_matches" type="submit">Update</button>
            </div>
        </form>
    </div>
    <div class="tab-pane fade mt-5" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <table class="table table-sm table-hover table-bordered table-dark">
            <thead align="center">
            <th scope="col">Team</th>
            <th scope="col">Matches</th>
            <th scope="col">Won</th>
            <th scope="col">Drawn</th>
            <th scope="col">Lost</th>
            <th scope="col"><abbr title="Goal scored">GS</abbr></th>
            <th scope="col"><abbr title="Goal conceded">GC</abbr></th>
            <th scope="col"><abbr title="Goal difference">GD</abbr></th>
            <th scope="col">
                <abbr title="Win - 3 Drawn - 1 Lost - 0">
                    Points
                </abbr>
            </th>
            </thead>
            <tbody align="center">
            {% for row in statistics %}
            <tr class="{% cycle 'bg-secondary' '' %}">
                <td align="left">{{ row.team.image_tag }}{{ row.team.title }}</td>
                <td>{{ row.matches }}</td>
                <td>{{ row.won }}</td>
                <td>{{ row.drawn }}</td>
                <td>{{ row.lost }}</td>
                <td>{{ row.goal_scored }}</td>
                <td>{{ row.goal_conceded }}</td>
                <td>{{ row.goal_scored|sub:row.goal_conceded }}</td>
                <td>{{ row.points }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endif %}
{% endblock %}

football/templates/football/tournaments.html
{% extends 'football/base.html' %}
{% block title %}
Tournaments
{% endblock %}

{% block body %}
<h1>Tournaments</h1>
<ul class="list-group">
    {% for tournament in tournaments %}
    <li class="list-group-item {% cycle '' 'list-group-item-secondary' %}">
        <a href="{% url 'football:tournaments' %}{{ tournament.id }}/">
                <span class="col-4">
                {{tournament.title}} {{ tournament.date_time }}
                </span>
            <span class="col-8">

            </span>
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}